Repository serum-390/soen390-team16-godzilla, pull requests merged in 2021-04, with the labels that each got.

#199 Fix for broken ECS deployment
  src/main/app/src/App.js
  src/main/app/src/components/SignUp.js
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/GodzillaUserRouter.java
  src/main/resources/sql/schema.pgsql
Labels: bug

#195 Authorization Frontend: per-user role and access level management
  src/main/app/src/components/Home.js
  src/main/app/src/components/NavBar.js
  src/main/app/src/components/SettingsPage.js
  src/main/app/src/components/inventory/InventoryCard.js
  src/main/app/src/components/settings-mini-pages/DisplaySettings.js
  src/main/app/src/components/settings-mini-pages/usermanagement/EditUsersCard.js
  src/main/app/src/components/settings-mini-pages/usermanagement/UserGrid.js
  src/main/app/src/components/settings-mini-pages/usermanagement/UserManagement.js
  src/main/app/src/components/settings-mini-pages/usermanagement/styles.js
  src/main/app/src/components/settings-mini-pages/usermanagement/utils.js
  src/main/app/src/styles/navBarSyles.js
  src/main/java/ca/serum390/godzilla/GodzillaApplication.java
  src/main/java/ca/serum390/godzilla/api/handlers/PermissionsHandler.java
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/PermissionsRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/ProductionManagerRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/UserRouter.java
  src/main/java/ca/serum390/godzilla/config/SecurityConfig.java
  src/main/java/ca/serum390/godzilla/config/StartupApplicationConfiguration.java
  src/main/java/ca/serum390/godzilla/domain/GodzillaUser.java
  src/main/resources/sql/schema.pgsql
  src/main/resources/static/images/user.png
  src/test/java/ca/serum390/godzilla/api/OrdersTests.java
  src/test/java/ca/serum390/godzilla/api/PermissionsTests.java
  src/test/java/ca/serum390/godzilla/api/VendersContactTests.java
Labels: Frontend, enhancement

#208 Help page and sub pages complete
  src/main/app/src/components/About.js
  src/main/app/src/components/Help.js
  src/main/app/src/components/helpMiniPages/AccountingHelp.js
  src/main/app/src/components/helpMiniPages/InventoryHelp.js
  src/main/app/src/components/helpMiniPages/NavBarHelp.js
  src/main/app/src/components/helpMiniPages/PlanningHelp.js
  src/main/app/src/components/helpMiniPages/ProductionHelp.js
  src/main/app/src/components/helpMiniPages/PurchasingHelp.js
  src/main/app/src/components/helpMiniPages/SalesHelp.js
  src/main/app/src/components/helpMiniPages/UserManagementHelp.js
  src/main/app/src/components/markDown/AboutUsPara.js
  src/main/app/src/misc/helpPageImages/accounting.png
  src/main/app/src/misc/helpPageImages/exporting.png
  src/main/app/src/misc/helpPageImages/navBar.png
  src/main/app/src/misc/helpPageImages/ordering.png
  src/main/app/src/misc/helpPageImages/planning.png
  src/main/app/src/misc/helpPageImages/userIcon.png
  src/main/app/src/misc/helpPageImages/userIcon2.png
  src/main/app/src/styles/themes.js
  src/main/java/ca/serum390/godzilla/api/filters/ReactRouterForwardFilter.java
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
Labels: Frontend

#204 Customer management (Conecting frontend to backend)
  src/main/app/src/Forms/AddressInput.js
  src/main/app/src/Forms/CustomerForm.js
  src/main/app/src/Forms/DeleteButton.js
  src/main/app/src/Forms/PhoneInput.js
  src/main/app/src/components/Sales.js
Labels: Frontend, duplicate, enhancement

#205 Production Frontend-to-Backend Connection
  src/main/app/src/Forms/NewProductionForm.js
  src/main/app/src/Forms/NewPurchaseOrderForm.js
  src/main/app/src/components/Production.js
  src/main/app/src/components/Purchasing.js
  src/main/java/ca/serum390/godzilla/api/handlers/ProductionManagerHandler.java
  src/main/java/ca/serum390/godzilla/api/routers/ProductionManagerRouter.java
  src/main/java/ca/serum390/godzilla/domain/manufacturing/PlannedProduct.java
Labels: Frontend

#214 Authorization frontend
  pom.xml
  src/main/app/public/index.html
  src/main/app/src/App.js
  src/main/app/src/components/Authentication.js
  src/main/app/src/components/Login.js
  src/main/app/src/components/SignUp.js
  src/main/java/ca/serum390/godzilla/api/filters/ReactRouterForwardFilter.java
  src/main/java/ca/serum390/godzilla/api/handlers/GodzillaUserHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/PermissionsHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/VendorContactHandler.java
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/GodzillaUserRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/UserRouter.java
  src/main/java/ca/serum390/godzilla/config/SecurityConfig.java
  src/main/java/ca/serum390/godzilla/config/StartupApplicationConfiguration.java
  src/main/java/ca/serum390/godzilla/data/repositories/GodzillaUserRepository.java
  src/main/java/ca/serum390/godzilla/domain/GodzillaUser.java
  src/main/resources/sql/data.pgsql
  src/main/resources/sql/schema.pgsql
Labels: Frontend

#216 Quality management frontend
  src/main/app/src/Forms/QualityForm.js
  src/main/app/src/components/inventory/Inventory.js
Labels: Frontend

#218 Small fixes to the login and signup pages
  src/main/app/src/components/Authentication.js
  src/main/java/ca/serum390/godzilla/config/SecurityConfig.java
Labels: Frontend
