Repository serum-390/soen390-team16-godzilla, pull requests merged in 2021-03, with the labels that each got.

#136 Settings page
  src/main/app/src/components/NavBar.js
  src/main/app/src/components/SettingsPage.js
  src/main/app/src/components/settingMiniPages/DisplaySettings.js
  src/main/app/src/components/settingMiniPages/UserManagement.js
Labels: Frontend

#137 Inventory UI enhanced
  src/main/app/src/Forms/InventoryForm.js
  src/main/app/src/components/inventory/Inventory.js
Labels: Frontend

#138 Sales page update, User Management page update
  src/main/app/src/Forms/CustomerForm.js
  src/main/app/src/Forms/PurchaseOrderDetailsForm.js
  src/main/app/src/Forms/UserForm.js
  src/main/app/src/components/Purchasing.js
  src/main/app/src/components/Sales.js
  src/main/app/src/components/settingMiniPages/UserManagement.js
Labels: Frontend, enhancement

#140 Orders
  src/main/java/ca/serum390/godzilla/api/handlers/OrderHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/SalesContactHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/SalesOrderHandler.java
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/OrderRouter.java
  src/main/java/ca/serum390/godzilla/config/DatabaseConfig.java
  src/main/java/ca/serum390/godzilla/data/repositories/OrdersRepository.java
  src/main/java/ca/serum390/godzilla/data/repositories/SalesContactRepository.java
  src/main/java/ca/serum390/godzilla/data/repositories/SalesOrderRepository.java
  src/main/java/ca/serum390/godzilla/domain/orders/Order.java
  src/main/java/ca/serum390/godzilla/domain/orders/SalesContact.java
  src/main/java/ca/serum390/godzilla/domain/purchasing/Purchase.java
  src/main/java/ca/serum390/godzilla/util/JsonToMapConverter.java
  src/main/java/ca/serum390/godzilla/util/MapToJsonConverter.java
  src/main/resources/sql/data.pgsql
  src/main/resources/sql/schema.pgsql
  src/test/java/ca/serum390/godzilla/api/OrdersTests.java
Labels: Backend

#153 Spring REST Docs + more unit tests
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/asciidoc/login-page.png
  src/main/java/ca/serum390/godzilla/api/handlers/GoodsHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/InventoryHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/ProductionHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/SalesContactHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/exceptions/NegativeSalesContactIdException.java
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/GoodsRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/InventoryRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/OrderRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/SalesContactRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/VendorContactRouter.java
  src/main/java/ca/serum390/godzilla/config/DatabaseConfig.java
  src/main/java/ca/serum390/godzilla/config/SecurityConfig.java
  src/main/java/ca/serum390/godzilla/config/StartupApplicationConfiguration.java
  src/main/java/ca/serum390/godzilla/data/repositories/InventoryRepository.java
  src/main/java/ca/serum390/godzilla/data/repositories/VendorContactRepository.java
  src/main/java/ca/serum390/godzilla/domain/inventory/Item.java
  src/main/java/ca/serum390/godzilla/domain/orders/SalesContact.java
  src/main/java/ca/serum390/godzilla/util/BuildableJsonMap.java
  src/main/java/ca/serum390/godzilla/util/BuildableMap.java
  src/main/resources/application.yml
  src/main/resources/sql/data.pgsql
  src/main/resources/sql/schema.pgsql
  src/test/java/ca/serum390/godzilla/BasicRestTests.java
  src/test/java/ca/serum390/godzilla/HttpRequestTests.java
  src/test/java/ca/serum390/godzilla/api/InventoryTests.java
  src/test/java/ca/serum390/godzilla/api/OrdersTests.java
  src/test/java/ca/serum390/godzilla/api/RestApiTests.java
  src/test/java/ca/serum390/godzilla/api/SalesContactTests.java
Labels: Backend, documentation, testing

#158 Sales page update
  src/main/app/src/Forms/CustomerForm.js
  src/main/app/src/Forms/NewSalesOrderForm.js
  src/main/app/src/components/Sales.js
Labels: Frontend, enhancement

#159 Production experimental
  src/main/app/src/components/Production.js
  src/main/java/ca/serum390/godzilla/api/handlers/OrderHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/PlannedProductHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/ProductionManagerHandler.java
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/PlannedProductRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/ProductionManagerRouter.java
  src/main/java/ca/serum390/godzilla/data/repositories/InventoryRepository.java
  src/main/java/ca/serum390/godzilla/data/repositories/OrdersRepository.java
  src/main/java/ca/serum390/godzilla/data/repositories/PlannedProductsRepository.java
  src/main/java/ca/serum390/godzilla/domain/manufacturing/PlannedProduct.java
  src/main/java/ca/serum390/godzilla/domain/orders/Order.java
  src/main/java/ca/serum390/godzilla/util/Events/InventoryEvent.java
  src/main/java/ca/serum390/godzilla/util/Events/InventoryEventHandler.java
  src/main/java/ca/serum390/godzilla/util/Events/ProductionEvent.java
  src/main/java/ca/serum390/godzilla/util/Events/ProductionEventHandler.java
  src/main/java/ca/serum390/godzilla/util/Events/PurchaseOrderEvent.java
  src/main/java/ca/serum390/godzilla/util/Events/PurchaseOrderEventHandler.java
  src/main/java/ca/serum390/godzilla/util/Events/eventsLog.log.lck
  src/main/resources/sql/data.pgsql
  src/main/resources/sql/schema.pgsql
  src/test/java/ca/serum390/godzilla/api/InventoryTests.java
  src/test/java/ca/serum390/godzilla/api/OrdersTests.java
Labels: Backend

#164 Removed placeholder from rest docs, changed event logger path, java 16 support
  .gitignore
  pom.xml
  src/main/asciidoc/index.adoc
  src/main/java/ca/serum390/godzilla/api/handlers/ProductionManagerHandler.java
  src/main/java/ca/serum390/godzilla/util/Events/eventsLog.log.lck
Labels: Backend, documentation

#160 Finished the about us page
  src/main/app/package.json
  src/main/app/src/components/About.js
  src/main/app/src/components/SettingsPage.js
  src/main/app/src/components/markDown/aboutUs.md
  src/main/app/yarn.lock
Labels: Frontend

#166 fixed the req for getting only the sales orders
  src/main/app/src/components/Purchasing.js
  src/main/app/src/components/Sales.js
  src/main/resources/sql/data.pgsql
Labels: Frontend, bug

#169 About us fixing
  src/main/app/src/components/About.js
  src/main/app/src/components/markDown/AboutUsPara.js
Labels: Frontend

#172 Accounting front end
  src/main/app/package.json
  src/main/app/src/Forms/CustomerForm.js
  src/main/app/src/Forms/InventoryForm.js
  src/main/app/src/Forms/NewPurchaseOrderForm.js
  src/main/app/src/components/Accounting.js
  src/main/app/src/components/Planning.js
  src/main/app/src/components/Production.js
  src/main/app/src/components/Purchasing.js
  src/main/app/src/components/Sales.js
  src/main/app/src/components/SettingsPage.js
  src/main/app/yarn.lock
Labels: Frontend

#188 Added dark mode functionality
  src/main/app/src/App.js
  src/main/app/src/components/settingMiniPages/DisplaySettings.js
  src/main/app/src/styles/themes.js
Labels: Frontend
