Repository serum-390/soen390-team16-godzilla, pull requests merged in 2021-02, with the labels that each got.

#47 Running Prototype - Sales view - for issue #38
  src/main/app/public/index.html
  src/main/app/src/App.js
  src/main/app/src/App.test.js
  src/main/app/src/components/About.js
  src/main/app/src/components/Accounting.js
  src/main/app/src/components/Help.js
  src/main/app/src/components/Home.js
  src/main/app/src/components/NavBar.js
  src/main/app/src/components/Planning.js
  src/main/app/src/components/Production.js
  src/main/app/src/components/Purchasing.js
  src/main/app/src/components/Sales.js
  src/main/app/src/components/UserAccount.js
  src/main/app/src/components/inventory/Inventory.js
  src/main/app/src/components/inventory/InventoryCard.js
  src/main/app/src/index.js
  src/main/app/src/misc/React-Spinner.css
  src/main/app/src/misc/logo.svg
  src/main/app/src/misc/reportWebVitals.js
  src/main/app/src/pages/About.js
  src/main/app/src/pages/Accounting.js
  src/main/app/src/pages/Help.js
  src/main/app/src/pages/Home.js
  src/main/app/src/pages/Planning.js
  src/main/app/src/pages/Production.js
  src/main/app/src/pages/Purchase.js
  src/main/app/src/pages/Sales.js
  src/main/app/src/pages/UserAccount.js
  src/main/app/src/styles/index.css
  src/main/app/src/styles/navBarSyles.js
  src/main/app/src/styles/salesPageStyles.js
  src/main/app/src/test/App.test.js
  src/main/app/src/test/setupTests.js
  src/main/java/ca/serum390/godzilla/configuration/RouteConfig.java
  src/main/java/ca/serum390/godzilla/handlers/InventoryHandler.java
  src/main/java/ca/serum390/godzilla/handlers/SalesHandler.java
Labels: enhancement

#48 Added the team name to the README.md
  .github/workflows/docker-publish.yml
  README.md
  docker/build-and-run.sh
Labels: documentation

#49 Add some boilerplate issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#53 Add a link to the Contributors wiki page to README.md
  README.md
Labels: documentation

#78 Update Readme
  README.md
Labels: documentation

#79 Fixing web app on mobile
  src/main/app/src/App.js
  src/main/app/src/components/NavBar.js
  src/main/app/src/components/NavBarMobile.js
  src/main/app/src/components/Sales.js
  src/main/app/src/components/inventory/Inventory.js
  src/main/app/src/components/inventory/InventoryCard.js
Labels: bug

#81 80 configure database
  .aws/godzilla-main-task.json
  .github/workflows/docker-publish.yml
  .github/workflows/maven.yml
  docker-compose.yml
  docker/build-and-run.sh
  docker/godzilla.dockerfile
  pom.xml
  src/main/app/src/components/About.js
  src/main/app/src/components/Accounting.js
  src/main/app/src/components/Home.js
  src/main/app/src/components/NavBar.js
  src/main/app/src/components/Planning.js
  src/main/app/src/components/Production.js
  src/main/app/src/components/Purchasing.js
  src/main/app/src/components/Sales.js
  src/main/app/src/components/inventory/Inventory.js
  src/main/java/ca/serum390/godzilla/configuration/DatabaseConfig.java
  src/main/java/ca/serum390/godzilla/configuration/ReactRouterForwardFilter.java
  src/main/java/ca/serum390/godzilla/configuration/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/configuration/routers/GoodsRouter.java
  src/main/java/ca/serum390/godzilla/experimental/BigBoi.java
  src/main/java/ca/serum390/godzilla/experimental/ComponentBoi.java
  src/main/java/ca/serum390/godzilla/experimental/ConfigBoi.java
  src/main/java/ca/serum390/godzilla/experimental/HelloHandler.java
  src/main/java/ca/serum390/godzilla/handlers/GoodsHandler.java
  src/main/java/ca/serum390/godzilla/manufacturing/Good.java
  src/main/java/ca/serum390/godzilla/repository/GoodsRepository.java
  src/main/resources/application.properties
  src/main/resources/application.yml
  src/main/resources/sql/data.pgsql
  src/main/resources/sql/schema.pgsql
  src/test/java/ca/serum390/godzilla/GodzillaApplicationTests.java
Labels: CI/CD, administrative

#92 Added Log out dialog box to logout button
  src/main/app/src/components/NavBar.js
  src/main/app/src/components/NavBarMobile.js
Labels: enhancement

#90 Added a dialog box for adding vendors in purchasing page
  src/main/app/package.json
  src/main/app/src/components/Purchasing.js
  src/main/app/yarn.lock
Labels: bug

#96 Refactored the backend packages - more clear project structure
  src/main/java/ca/serum390/godzilla/api/filters/ReactRouterForwardFilter.java
  src/main/java/ca/serum390/godzilla/api/handlers/GoodsHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/InventoryHandler.java
  src/main/java/ca/serum390/godzilla/api/handlers/SalesHandler.java
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
  src/main/java/ca/serum390/godzilla/api/routers/GoodsRouter.java
  src/main/java/ca/serum390/godzilla/config/DatabaseConfig.java
  src/main/java/ca/serum390/godzilla/data/repositories/GoodsRepository.java
  src/main/java/ca/serum390/godzilla/domain/accounting/Account.java
  src/main/java/ca/serum390/godzilla/domain/manufacturing/Good.java
  src/main/java/ca/serum390/godzilla/domain/planning/Plan.java
  src/main/java/ca/serum390/godzilla/domain/purchasing/Purchase.java
  src/main/java/ca/serum390/godzilla/domain/sales/Sale.java
  src/main/java/ca/serum390/godzilla/handlers/InventoryHandler.java
  src/main/java/ca/serum390/godzilla/util/BuildableMap.java
  src/main/java/ca/serum390/godzilla/util/experimental/BigBoi.java
  src/main/java/ca/serum390/godzilla/util/experimental/ComponentBoi.java
  src/main/java/ca/serum390/godzilla/util/experimental/ConfigBoi.java
  src/main/java/ca/serum390/godzilla/util/experimental/HelloHandler.java
Labels: Backend

#97 Fixed the multiple insertion into goods_type table
  docker/build-and-run.sh
  src/main/resources/sql/data.pgsql
  src/main/resources/sql/schema.pgsql
Labels: CI/CD

#98 Edited the Sales page
  src/main/app/src/Forms/CustomerForm.js
  src/main/app/src/components/Sales.js
Labels: Frontend, enhancement

#101 Added custom GODZILLA logo to the Readme, the wiki, and to the web app
  README.md
  src/main/app/public/android-chrome-192x192.png
  src/main/app/public/android-chrome-512x512.png
  src/main/app/public/apple-touch-icon.png
  src/main/app/public/favicon-16x16.png
  src/main/app/public/favicon-32x32.png
  src/main/app/public/favicon.ico
  src/main/app/public/index.html
  src/main/app/public/logo192.png
  src/main/app/public/logo512.png
  src/main/app/public/manifest.json
  src/main/app/src/components/NavBar.js
  src/main/app/src/components/NavBarMobile.js
  src/main/app/src/styles/navBarSyles.js
  src/main/app/src/util/hooks.js
  src/main/resources/static/images/favicon_io/android-chrome-192x192.png
  src/main/resources/static/images/favicon_io/android-chrome-512x512.png
  src/main/resources/static/images/favicon_io/apple-touch-icon.png
  src/main/resources/static/images/favicon_io/favicon-16x16.png
  src/main/resources/static/images/favicon_io/favicon-32x32.png
  src/main/resources/static/images/favicon_io/favicon.ico
  src/main/resources/static/images/favicon_io/site.webmanifest
  src/main/resources/static/images/logo-and-name.png
  src/main/resources/static/images/logo-min.png
  src/main/resources/static/images/main-on-transparent-min.png
  src/main/resources/static/images/name-logo-min.png
Labels: documentation

#103 Fixed favicon.ico and other resources to be served by Spring
  src/main/app/public/index.html
  src/main/app/public/resources/favicon.ico
  src/main/app/public/resources/logo192.png
  src/main/app/public/resources/logo512.png
  src/main/app/public/resources/manifest.json
  src/main/java/ca/serum390/godzilla/api/routers/ApiRouter.java
Labels: Backend

#106 Refactored Dialog box from Purchasing view
  src/main/app/src/components/Purchasing.js
  src/main/app/src/components/forms/AddressInput.js
  src/main/app/src/components/forms/PhoneInput.js
Labels: Frontend

#108 Updated the customer Form
  src/main/app/src/Forms/CustomerForm.js
Labels: Frontend, enhancement

#117 Purchase orders
  src/main/app/src/Forms/NewPurchaseOrderForm.js
  src/main/app/src/Forms/PurchaseOrderDetailsForm.js
  src/main/app/src/Forms/VendorDetailsForm.js
  src/main/app/src/components/Purchasing.js
  src/main/app/src/components/forms/DeleteButton.js
  src/main/java/ca/serum390/godzilla/domain/planning/Plan.java
Labels: Frontend, enhancement

#119 Inventory Frontend and Update operation
  src/main/app/src/Forms/InventoryForm.js
  src/main/app/src/components/inventory/Inventory.js
  src/main/app/src/components/inventory/InventoryCard.js
  src/main/java/ca/serum390/godzilla/api/handlers/InventoryHandler.java
  src/main/java/ca/serum390/godzilla/api/routers/InventoryRouter.java
  src/main/java/ca/serum390/godzilla/data/repositories/InventoryRepository.java
  src/main/resources/sql/data.pgsql
  src/main/resources/sql/schema.pgsql
Labels: Backend, Frontend
